export const NEWARRIVALS_LIST_REQUEST = 'NEWARRIVALS_LIST_REQUEST';
export const NEWARRIVALS_LIST_SUCCESS = 'NEWARRIVALS_LIST_SUCCESS';
export const NEWARRIVALS_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const NEWARRIVALS_DETAILS_REQUEST = 'NEWARRIVALS_DETAILS_REQUEST';
export const NEWARRIVALS_DETAILS_SUCCESS = 'NEWARRIVALS_DETAILS_SUCCESS';
export const NEWARRIVALS_DETAILS_FAIL = 'NEWARRIVALS_DETAILS_FAIL';